#ifndef __GL_DLPROTO_H__
#define __GL_DLPROTO_H__
/**************************************************************************
 *									  *
 * 		 Copyright (C) 1984, Silicon Graphics, Inc.		  *
 *									  *
 *  These coded instructions, statements, and computer programs  contain  *
 *  unpublished  proprietary  information of Silicon Graphics, Inc., and  *
 *  are protected by Federal copyright law.  They  may  not be disclosed  *
 *  to  third  parties  or copied or duplicated in any form, in whole or  *
 *  in part, without the prior written consent of Silicon Graphics, Inc.  *
 *									  *
 **************************************************************************/

extern void	gl_i_backbuffer( Boolean );
extern void	gl_c_backbuffer( Boolean );
extern void	gl_i_bbox2( Screencoord, Screencoord, Coord, Coord, Coord, Coord );
extern void	gl_c_bbox2( Screencoord, Screencoord, Coord, Coord, Coord, Coord );
extern void	gl_i_bbox2i( Screencoord, Screencoord, Icoord, Icoord, Icoord, Icoord );
extern void	gl_c_bbox2i( Screencoord, Screencoord, Icoord, Icoord, Icoord, Icoord );
extern void	gl_i_callobj( Object );
extern void	gl_c_callobj( Object );
extern void	gl_i_charstr( String );
extern void	gl_c_charstr( String );
extern void	gl_i_clear( void );
extern void	gl_c_clear( void );
extern void	gl_i_cmov( Coord, Coord, Coord );
extern void	gl_c_cmov( Coord, Coord, Coord );
extern void	gl_i_cmov2( Coord, Coord );
extern void	gl_c_cmov2( Coord, Coord );
extern void	gl_i_cmov2i( Icoord, Icoord );
extern void	gl_c_cmov2i( Icoord, Icoord );
extern void	gl_i_cmovi( Icoord, Icoord, Icoord );
extern void	gl_c_cmovi( Icoord, Icoord, Icoord );
extern void	gl_i_color( Colorindex );
extern void	gl_c_color( Colorindex );
extern void	gl_i_curveit( short );
extern void	gl_c_curveit( short );
extern void	gl_i_draw( Coord, Coord, Coord );
extern void	gl_c_draw( Coord, Coord, Coord );
extern void	gl_i_draw2( Coord, Coord );
extern void	gl_c_draw2( Coord, Coord );
extern void	gl_i_draw2i( Icoord, Icoord );
extern void	gl_c_draw2i( Icoord, Icoord );
extern void	gl_i_drawi( Icoord, Icoord, Icoord );
extern void	gl_c_drawi( Icoord, Icoord, Icoord );
extern void	gl_i_font( short );
extern void	gl_c_font( short );
extern void	gl_i_frontbuffer( Boolean );
extern void	gl_c_frontbuffer( Boolean );
extern void	gl_i_linewidth( short );
extern void	gl_c_linewidth( short );
extern void	gl_i_loadmatrix( const Matrix );
extern void	gl_c_loadmatrix( const Matrix );
extern void	gl_i_lsbackup( Boolean );
extern void	gl_c_lsbackup( Boolean );
extern void	gl_i_move( Coord, Coord, Coord );
extern void	gl_c_move( Coord, Coord, Coord );
extern void	gl_i_move2( Coord, Coord );
extern void	gl_c_move2( Coord, Coord );
extern void	gl_i_move2i( Icoord, Icoord );
extern void	gl_c_move2i( Icoord, Icoord );
extern void	gl_i_movei( Icoord, Icoord, Icoord );
extern void	gl_c_movei( Icoord, Icoord, Icoord );
extern void	gl_i_multmatrix( const Matrix );
extern void	gl_c_multmatrix( const Matrix );
extern void	gl_i_pnt( Coord, Coord, Coord );
extern void	gl_c_pnt( Coord, Coord, Coord );
extern void	gl_i_pnt2( Coord, Coord );
extern void	gl_c_pnt2( Coord, Coord );
extern void	gl_i_pnt2i( Icoord, Icoord );
extern void	gl_c_pnt2i( Icoord, Icoord );
extern void	gl_i_pnti( Icoord, Icoord, Icoord );
extern void	gl_c_pnti( Icoord, Icoord, Icoord );
extern void	gl_i_polf( long, const Coord[][3] );
extern void	gl_c_polf( long, const Coord[][3] );
extern void	gl_i_polf2( long, const Coord[][2] );
extern void	gl_c_polf2( long, const Coord[][2] );
extern void	gl_i_polf2i( long, const Icoord[][2] );
extern void	gl_c_polf2i( long, const Icoord[][2] );
extern void	gl_i_polfi( long, const Icoord[][3] );
extern void	gl_c_polfi( long, const Icoord[][3] );
extern void	gl_i_poly( long, const Coord[][3] );
extern void	gl_c_poly( long, const Coord[][3] );
extern void	gl_i_poly2( long, const Coord[][2] );
extern void	gl_c_poly2( long, const Coord[][2] );
extern void	gl_i_poly2i( long, const Icoord[][2] );
extern void	gl_c_poly2i( long, const Icoord[][2] );
extern void	gl_i_polyi( long, const Icoord[][3] );
extern void	gl_c_polyi( long, const Icoord[][3] );
extern void	gl_i_popmatrix( void );
extern void	gl_c_popmatrix( void );
extern void	gl_i_pushmatrix( void );
extern void	gl_c_pushmatrix( void );
extern void	gl_i_rect( Coord, Coord, Coord, Coord );
extern void	gl_c_rect( Coord, Coord, Coord, Coord );
extern void	gl_i_rectf( Coord, Coord, Coord, Coord );
extern void	gl_c_rectf( Coord, Coord, Coord, Coord );
extern void	gl_i_rectfi( Icoord, Icoord, Icoord, Icoord );
extern void	gl_c_rectfi( Icoord, Icoord, Icoord, Icoord );
extern void	gl_i_recti( Icoord, Icoord, Icoord, Icoord );
extern void	gl_c_recti( Icoord, Icoord, Icoord, Icoord );
extern void	gl_i_resetls( Boolean );
extern void	gl_c_resetls( Boolean );
extern void	gl_i_RGBcolor( short, short, short );
extern void	gl_c_RGBcolor( short, short, short );
extern void	gl_i_RGBwritemask( short, short, short );
extern void	gl_c_RGBwritemask( short, short, short );
extern void	gl_i_rotate( Angle, char );
extern void	gl_c_rotate( Angle, char );
extern void	gl_i_scale( float, float, float );
extern void	gl_c_scale( float, float, float );
extern void	gl_i_setlinestyle( short );
extern void	gl_c_setlinestyle( short );
extern void	gl_i_swapbuffers( void );
extern void	gl_c_swapbuffers( void );
extern void	gl_i_swapinterval( short );
extern void	gl_c_swapinterval( short );
extern void	gl_i_translate( Coord, Coord, Coord );
extern void	gl_c_translate( Coord, Coord, Coord );
extern void	gl_i_writemask( Colorindex );
extern void	gl_c_writemask( Colorindex );
extern void	gl_i_bbox2s( Screencoord, Screencoord, Scoord, Scoord, Scoord, Scoord );
extern void	gl_c_bbox2s( Screencoord, Screencoord, Scoord, Scoord, Scoord, Scoord );
extern void	gl_i_cmov2s( Scoord, Scoord );
extern void	gl_c_cmov2s( Scoord, Scoord );
extern void	gl_i_cmovs( Scoord, Scoord, Scoord );
extern void	gl_c_cmovs( Scoord, Scoord, Scoord );
extern void	gl_i_curvebasis( short );
extern void	gl_c_curvebasis( short );
extern void	gl_i_curveprecision( short );
extern void	gl_c_curveprecision( short );
extern void	gl_i_depthcue( Boolean );
extern void	gl_c_depthcue( Boolean );
extern void	gl_i_draw2s( Scoord, Scoord );
extern void	gl_c_draw2s( Scoord, Scoord );
extern void	gl_i_draws( Scoord, Scoord, Scoord );
extern void	gl_c_draws( Scoord, Scoord, Scoord );
extern void	gl_i_initnames( void );
extern void	gl_c_initnames( void );
extern void	gl_i_loadname( short );
extern void	gl_c_loadname( short );
extern void	gl_i_lsrepeat( long );
extern void	gl_c_lsrepeat( long );
extern void	gl_i_move2s( Scoord, Scoord );
extern void	gl_c_move2s( Scoord, Scoord );
extern void	gl_i_moves( Scoord, Scoord, Scoord );
extern void	gl_c_moves( Scoord, Scoord, Scoord );
extern void	gl_i_passthrough( short );
extern void	gl_c_passthrough( short );
extern void	gl_i_patchbasis( long, long );
extern void	gl_c_patchbasis( long, long );
extern void	gl_i_patchprecision( long, long );
extern void	gl_c_patchprecision( long, long );
extern void	gl_i_pclos( void );
extern void	gl_c_pclos( void );
extern void	gl_i_pdr( Coord, Coord, Coord );
extern void	gl_c_pdr( Coord, Coord, Coord );
extern void	gl_i_pdr2( Coord, Coord );
extern void	gl_c_pdr2( Coord, Coord );
extern void	gl_i_pdri( Icoord, Icoord, Icoord );
extern void	gl_c_pdri( Icoord, Icoord, Icoord );
extern void	gl_i_pdr2i( Icoord, Icoord );
extern void	gl_c_pdr2i( Icoord, Icoord );
extern void	gl_i_pdrs( Scoord, Scoord, Scoord );
extern void	gl_c_pdrs( Scoord, Scoord, Scoord );
extern void	gl_i_pdr2s( Scoord, Scoord );
extern void	gl_c_pdr2s( Scoord, Scoord );
extern void	gl_i_polf2s( long, const Scoord[][2] );
extern void	gl_c_polf2s( long, const Scoord[][2] );
extern void	gl_i_polfs( long, const Scoord[][3] );
extern void	gl_c_polfs( long, const Scoord[][3] );
extern void	gl_i_poly2s( long, const Scoord[][2] );
extern void	gl_c_poly2s( long, const Scoord[][2] );
extern void	gl_i_polys( long, const Scoord[][3] );
extern void	gl_c_polys( long, const Scoord[][3] );
extern void	gl_i_pmv( Coord, Coord, Coord );
extern void	gl_c_pmv( Coord, Coord, Coord );
extern void	gl_i_pmv2( Coord, Coord );
extern void	gl_c_pmv2( Coord, Coord );
extern void	gl_i_pmvi( Icoord, Icoord, Icoord );
extern void	gl_c_pmvi( Icoord, Icoord, Icoord );
extern void	gl_i_pmv2i( Icoord, Icoord );
extern void	gl_c_pmv2i( Icoord, Icoord );
extern void	gl_i_pmvs( Scoord, Scoord, Scoord );
extern void	gl_c_pmvs( Scoord, Scoord, Scoord );
extern void	gl_i_pmv2s( Scoord, Scoord );
extern void	gl_c_pmv2s( Scoord, Scoord );
extern void	gl_i_pnt2s( Scoord, Scoord );
extern void	gl_c_pnt2s( Scoord, Scoord );
extern void	gl_i_pnts( Scoord, Scoord, Scoord );
extern void	gl_c_pnts( Scoord, Scoord, Scoord );
extern void	gl_i_popname( void );
extern void	gl_c_popname( void );
extern void	gl_i_pushname( short );
extern void	gl_c_pushname( short );
extern void	gl_i_rdr( Coord, Coord, Coord );
extern void	gl_c_rdr( Coord, Coord, Coord );
extern void	gl_i_rdr2( Coord, Coord );
extern void	gl_c_rdr2( Coord, Coord );
extern void	gl_i_rdri( Icoord, Icoord, Icoord );
extern void	gl_c_rdri( Icoord, Icoord, Icoord );
extern void	gl_i_rdr2i( Icoord, Icoord );
extern void	gl_c_rdr2i( Icoord, Icoord );
extern void	gl_i_rdrs( Scoord, Scoord, Scoord );
extern void	gl_c_rdrs( Scoord, Scoord, Scoord );
extern void	gl_i_rdr2s( Scoord, Scoord );
extern void	gl_c_rdr2s( Scoord, Scoord );
extern void	gl_i_rmv( Coord, Coord, Coord );
extern void	gl_c_rmv( Coord, Coord, Coord );
extern void	gl_i_rmv2( Coord, Coord );
extern void	gl_c_rmv2( Coord, Coord );
extern void	gl_i_rmvi( Icoord, Icoord, Icoord );
extern void	gl_c_rmvi( Icoord, Icoord, Icoord );
extern void	gl_i_rmv2i( Icoord, Icoord );
extern void	gl_c_rmv2i( Icoord, Icoord );
extern void	gl_i_rmvs( Scoord, Scoord, Scoord );
extern void	gl_c_rmvs( Scoord, Scoord, Scoord );
extern void	gl_i_rmv2s( Scoord, Scoord );
extern void	gl_c_rmv2s( Scoord, Scoord );
extern void	gl_i_rpdr( Coord, Coord, Coord );
extern void	gl_c_rpdr( Coord, Coord, Coord );
extern void	gl_i_rpdr2( Coord, Coord );
extern void	gl_c_rpdr2( Coord, Coord );
extern void	gl_i_rpdri( Icoord, Icoord, Icoord );
extern void	gl_c_rpdri( Icoord, Icoord, Icoord );
extern void	gl_i_rpdr2i( Icoord, Icoord );
extern void	gl_c_rpdr2i( Icoord, Icoord );
extern void	gl_i_rpdrs( Scoord, Scoord, Scoord );
extern void	gl_c_rpdrs( Scoord, Scoord, Scoord );
extern void	gl_i_rpdr2s( Scoord, Scoord );
extern void	gl_c_rpdr2s( Scoord, Scoord );
extern void	gl_i_rpmv( Coord, Coord, Coord );
extern void	gl_c_rpmv( Coord, Coord, Coord );
extern void	gl_i_rpmv2( Coord, Coord );
extern void	gl_c_rpmv2( Coord, Coord );
extern void	gl_i_rpmvi( Icoord, Icoord, Icoord );
extern void	gl_c_rpmvi( Icoord, Icoord, Icoord );
extern void	gl_i_rpmv2i( Icoord, Icoord );
extern void	gl_c_rpmv2i( Icoord, Icoord );
extern void	gl_i_rpmvs( Scoord, Scoord, Scoord );
extern void	gl_c_rpmvs( Scoord, Scoord, Scoord );
extern void	gl_i_rpmv2s( Scoord, Scoord );
extern void	gl_c_rpmv2s( Scoord, Scoord );
extern void	gl_i_splf( long, const Coord[][3], const Colorindex[] );
extern void	gl_c_splf( long, const Coord[][3], const Colorindex[] );
extern void	gl_i_splf2( long, const Coord[][2], const Colorindex[] );
extern void	gl_c_splf2( long, const Coord[][2], const Colorindex[] );
extern void	gl_i_splfi( long, const Icoord[][3], const Colorindex[] );
extern void	gl_c_splfi( long, const Icoord[][3], const Colorindex[] );
extern void	gl_i_splf2i( long, const Icoord[][2], const Colorindex[] );
extern void	gl_c_splf2i( long, const Icoord[][2], const Colorindex[] );
extern void	gl_i_splfs( long, const Scoord[][3], const Colorindex[] );
extern void	gl_c_splfs( long, const Scoord[][3], const Colorindex[] );
extern void	gl_i_splf2s( long, const Scoord[][2], const Colorindex[] );
extern void	gl_c_splf2s( long, const Scoord[][2], const Colorindex[] );
extern void	gl_i_xfpt( Coord, Coord, Coord );
extern void	gl_c_xfpt( Coord, Coord, Coord );
extern void	gl_i_xfpti( Icoord, Icoord, Icoord );
extern void	gl_c_xfpti( Icoord, Icoord, Icoord );
extern void	gl_i_xfpts( Scoord, Scoord, Scoord );
extern void	gl_c_xfpts( Scoord, Scoord, Scoord );
extern void	gl_i_xfpt2( Coord, Coord );
extern void	gl_c_xfpt2( Coord, Coord );
extern void	gl_i_xfpt2i( Icoord, Icoord );
extern void	gl_c_xfpt2i( Icoord, Icoord );
extern void	gl_i_xfpt2s( Scoord, Scoord );
extern void	gl_c_xfpt2s( Scoord, Scoord );
extern void	gl_i_xfpt4( Coord, Coord, Coord, Coord );
extern void	gl_c_xfpt4( Coord, Coord, Coord, Coord );
extern void	gl_i_xfpt4i( Icoord, Icoord, Icoord, Icoord );
extern void	gl_c_xfpt4i( Icoord, Icoord, Icoord, Icoord );
extern void	gl_i_xfpt4s( Scoord, Scoord, Scoord, Scoord );
extern void	gl_c_xfpt4s( Scoord, Scoord, Scoord, Scoord );
extern void	gl_i_zbuffer( Boolean );
extern void	gl_c_zbuffer( Boolean );
extern void	gl_i_setpattern( short );
extern void	gl_c_setpattern( short );
extern void	gl_i_zclear( void );
extern void	gl_c_zclear( void );
extern void	gl_i_patchcurves( long, long );
extern void	gl_c_patchcurves( long, long );
extern void	gl_i_backface( Boolean );
extern void	gl_c_backface( Boolean );
extern void	gl_i_rects( Scoord, Scoord, Scoord, Scoord );
extern void	gl_c_rects( Scoord, Scoord, Scoord, Scoord );
extern void	gl_i_rectfs( Scoord, Scoord, Scoord, Scoord );
extern void	gl_c_rectfs( Scoord, Scoord, Scoord, Scoord );
extern void	gl_i_rcrv( const Coord[4][4] );
extern void	gl_c_rcrv( const Coord[4][4] );
extern void	gl_i_rcrvn( long, const Coord[][4] );
extern void	gl_c_rcrvn( long, const Coord[][4] );
extern void	gl_i_rpatch( const Matrix, const Matrix, const Matrix, const Matrix );
extern void	gl_c_rpatch( const Matrix, const Matrix, const Matrix, const Matrix );
extern void	gl_i_rot( float, char );
extern void	gl_c_rot( float, char );
extern void	gl_i_concave( Boolean );
extern void	gl_c_concave( Boolean );
extern void	gl_i_shademodel( long );
extern void	gl_c_shademodel( long );
extern void	gl_i_lmbind( short, short );
extern void	gl_c_lmbind( short, short );
extern void	gl_i_mmode( short );
extern void	gl_c_mmode( short );
extern void	gl_i_normal( const Coord[3] );
extern void	gl_c_normal( const Coord[3] );
extern void	gl_i_bgnclosedline( void );
extern void	gl_c_bgnclosedline( void );
extern void	gl_i_bgnline( void );
extern void	gl_c_bgnline( void );
extern void	gl_i_bgnpoint( void );
extern void	gl_c_bgnpoint( void );
extern void	gl_i_bgnpolygon( void );
extern void	gl_c_bgnpolygon( void );
extern void	gl_i_bgntmesh( void );
extern void	gl_c_bgntmesh( void );
extern void	gl_i_blendfunction( long, long );
extern void	gl_c_blendfunction( long, long );
extern void	gl_i_c3f( const float[3] );
extern void	gl_c_c3f( const float[3] );
extern void	gl_i_c3i( const long[3] );
extern void	gl_c_c3i( const long[3] );
extern void	gl_i_c3s( const short[3] );
extern void	gl_c_c3s( const short[3] );
extern void	gl_i_c4f( const float[4] );
extern void	gl_c_c4f( const float[4] );
extern void	gl_i_c4i( const long[4] );
extern void	gl_c_c4i( const long[4] );
extern void	gl_i_c4s( const short[4] );
extern void	gl_c_c4s( const short[4] );
extern void	gl_i_cpack( unsigned long );
extern void	gl_c_cpack( unsigned long );
extern void	gl_i_czclear( unsigned long, long );
extern void	gl_c_czclear( unsigned long, long );
extern void	gl_i_endclosedline( void );
extern void	gl_c_endclosedline( void );
extern void	gl_i_endline( void );
extern void	gl_c_endline( void );
extern void	gl_i_endpoint( void );
extern void	gl_c_endpoint( void );
extern void	gl_i_endpolygon( void );
extern void	gl_c_endpolygon( void );
extern void	gl_i_endtmesh( void );
extern void	gl_c_endtmesh( void );
extern void	gl_i_n3f( const float[3] );
extern void	gl_c_n3f( const float[3] );
extern void	gl_i_swaptmesh( void );
extern void	gl_c_swaptmesh( void );
extern void	gl_i_v2d( const double[2] );
extern void	gl_c_v2d( const double[2] );
extern void	gl_i_v2f( const float[2] );
extern void	gl_c_v2f( const float[2] );
extern void	gl_i_v2i( const long[2] );
extern void	gl_c_v2i( const long[2] );
extern void	gl_i_v2s( const short[2] );
extern void	gl_c_v2s( const short[2] );
extern void	gl_i_v3d( const double[3] );
extern void	gl_c_v3d( const double[3] );
extern void	gl_i_v3f( const float[3] );
extern void	gl_c_v3f( const float[3] );
extern void	gl_i_v3i( const long[3] );
extern void	gl_c_v3i( const long[3] );
extern void	gl_i_v3s( const short[3] );
extern void	gl_c_v3s( const short[3] );
extern void	gl_i_v4d( const double[4] );
extern void	gl_c_v4d( const double[4] );
extern void	gl_i_v4f( const float[4] );
extern void	gl_c_v4f( const float[4] );
extern void	gl_i_v4i( const long[4] );
extern void	gl_c_v4i( const long[4] );
extern void	gl_i_v4s( const short[4] );
extern void	gl_c_v4s( const short[4] );
extern void	gl_i_wmpack( unsigned long );
extern void	gl_c_wmpack( unsigned long );
extern void	gl_i_zdraw( Boolean );
extern void	gl_c_zdraw( Boolean );
extern void	gl_i_zfunction( long );
extern void	gl_c_zfunction( long );
extern void	gl_i_zsource( long );
extern void	gl_c_zsource( long );
extern void	gl_i_zwritemask( unsigned long );
extern void	gl_c_zwritemask( unsigned long );
extern void	gl_i_pntsmooth( unsigned long );
extern void	gl_c_pntsmooth( unsigned long );
extern void	gl_i_linesmooth( unsigned long );
extern void	gl_c_linesmooth( unsigned long );
extern void	gl_i_subpixel( Boolean );
extern void	gl_c_subpixel( Boolean );
extern void	gl_i_sbox( Coord, Coord, Coord, Coord );
extern void	gl_c_sbox( Coord, Coord, Coord, Coord );
extern void	gl_i_sboxf( Coord, Coord, Coord, Coord );
extern void	gl_c_sboxf( Coord, Coord, Coord, Coord );
extern void	gl_i_sboxfi( Icoord, Icoord, Icoord, Icoord );
extern void	gl_c_sboxfi( Icoord, Icoord, Icoord, Icoord );
extern void	gl_i_sboxi( Icoord, Icoord, Icoord, Icoord );
extern void	gl_c_sboxi( Icoord, Icoord, Icoord, Icoord );
extern void	gl_i_sboxs( Scoord, Scoord, Scoord, Scoord );
extern void	gl_c_sboxs( Scoord, Scoord, Scoord, Scoord );
extern void	gl_i_sboxfs( Scoord, Scoord, Scoord, Scoord );
extern void	gl_c_sboxfs( Scoord, Scoord, Scoord, Scoord );
extern void	gl_i_lmcolor( long );
extern void	gl_c_lmcolor( long );
extern void	gl_i_logicop( long );
extern void	gl_c_logicop( long );
extern void	gl_i_colorf( float );
extern void	gl_c_colorf( float );
extern void	gl_i_frontface( Boolean );
extern void	gl_c_frontface( Boolean );
extern void	gl_i_bgnqstrip( void );
extern void	gl_c_bgnqstrip( void );
extern void	gl_i_endqstrip( void );
extern void	gl_c_endqstrip( void );
extern void	gl_i_gl_scrrect( long, long, long, long, long );
extern void	gl_c_gl_scrrect( long, long, long, long, long );
extern void	gl_i_nmode( long );
extern void	gl_c_nmode( long );
extern void	gl_i_t2f( const float[2] );
extern void	gl_c_t2f( const float[2] );
extern void	gl_i_t2d( const double[2] );
extern void	gl_c_t2d( const double[2] );
extern void	gl_i_t2i( const long[2] );
extern void	gl_c_t2i( const long[2] );
extern void	gl_i_t2s( const short[2] );
extern void	gl_c_t2s( const short[2] );
extern void	gl_i_sclear( unsigned long );
extern void	gl_c_sclear( unsigned long );
extern void	gl_i_acbuf( long, float );
extern void	gl_c_acbuf( long, float );
extern void	gl_i_clipplane( long, long, const float[] );
extern void	gl_c_clipplane( long, long, const float[] );
extern void	gl_i_fogvertex( long, const float[32] );
extern void	gl_c_fogvertex( long, const float[32] );
extern void	gl_i_scrbox( long );
extern void	gl_c_scrbox( long );
extern void	gl_i_stencil( long, unsigned long, long, unsigned long, long, long, long );
extern void	gl_c_stencil( long, unsigned long, long, unsigned long, long, long, long );
extern void	gl_i_swritemask( unsigned long );
extern void	gl_c_swritemask( unsigned long );
extern void	gl_i_pixmode( long, long );
extern void	gl_c_pixmode( long, long );
extern void	gl_i_polymode( long );
extern void	gl_c_polymode( long );
extern void	gl_i_afunction( long, long );
extern void	gl_c_afunction( long, long );
extern void	gl_i_tevbind( long, long );
extern void	gl_c_tevbind( long, long );
extern void	gl_i_texbind( long, long );
extern void	gl_c_texbind( long, long );
extern void	gl_i_mswapbuffers( long );
extern void	gl_c_mswapbuffers( long );
extern void	gl_i_polysmooth( long );
extern void	gl_c_polysmooth( long );
extern void	gl_i_scrsubdivide( long, const float[] );
extern void	gl_c_scrsubdivide( long, const float[] );
extern void	gl_i_texgen( long, long, const float[] );
extern void	gl_c_texgen( long, long, const float[] );
extern void	gl_i_linewidthf( float );
extern void	gl_c_linewidthf( float );
extern void	gl_i_pntsize( short );
extern void	gl_c_pntsize( short );
extern void	gl_i_pntsizef( float );
extern void	gl_c_pntsizef( float );
extern void	gl_i_pixmodef( long, float );
extern void	gl_c_pixmodef( long, float );
extern void	gl_i_dither( long );
extern void	gl_c_dither( long );
extern void	gl_i_lcharstr( long, Lstring );
extern void	gl_c_lcharstr( long, Lstring );
extern void	gl_i_lchstr( long, Lstring, long );
extern void	gl_c_lchstr( long, Lstring, long );
extern void	gl_i_t3f( const float[3] );
extern void	gl_c_t3f( const float[3] );
extern void	gl_i_t3d( const double[3] );
extern void	gl_c_t3d( const double[3] );
extern void	gl_i_t3i( const long[3] );
extern void	gl_c_t3i( const long[3] );
extern void	gl_i_t3s( const short[3] );
extern void	gl_c_t3s( const short[3] );
extern void	gl_i_t4f( const float[4] );
extern void	gl_c_t4f( const float[4] );
extern void	gl_i_t4d( const double[4] );
extern void	gl_c_t4d( const double[4] );
extern void	gl_i_t4i( const long[4] );
extern void	gl_c_t4i( const long[4] );
extern void	gl_i_t4s( const short[4] );
extern void	gl_c_t4s( const short[4] );
extern void	gl_i_mssample( long );
extern void	gl_c_mssample( long );
extern void	gl_i_leftbuffer( Boolean );
extern void	gl_c_leftbuffer( Boolean );
extern void	gl_i_rightbuffer( Boolean );
extern void	gl_c_rightbuffer( Boolean );
extern void	gl_i_blendcolor( float, float, float, float );
extern void	gl_c_blendcolor( float, float, float, float );
extern void	gl_i_msalpha( long );
extern void	gl_c_msalpha( long );
extern void	gl_i_msmask( float, Boolean );
extern void	gl_c_msmask( float, Boolean );
extern void	gl_i_mspattern( long );
extern void	gl_c_mspattern( long );
extern void	gl_i_multisample( Boolean );
extern void	gl_c_multisample( Boolean );
extern void	gl_i_tlutbind( long, long );
extern void	gl_c_tlutbind( long, long );
extern void	gl_i_displacepolygon( float );
extern void	gl_c_displacepolygon( float );

#endif /* !__GL_DLPROTO_H__ */
